name: pdns-recursor

services:
  recurse-1:
    restart: unless-stopped
    image: local/pdns-recursor
    ports:
      - '<ip-address>:53:53/tcp' # plain dns over tcp v4
      - '<ip-address>:53:53/udp' # plain dns over udp v4
      - '[<ipv6-address>]:53:53/tcp' # plain dns over tcp v4
      - '[<ipv6-address>]:53:53/udp' # plain dns over udp v4
      - '<ip-address>:8083:8083/tcp' #Web Stats
    sysctls:
      - net.ipv6.route.max_size=16384
    volumes:
      - ./powerdns/recursor.conf:/etc/powerdns/recursor.conf

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
