name: Build DNS Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
    paths:
      - "Dockerized-DNS-Server/**/Dockerfile"
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
jobs:
  powerdns-recursor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'

      - name: Convert repository name to lowercase
        run: echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push PowerDNS Recursor
        id: build-recursor
        uses: docker/build-push-action@v5
        with:
          context: Dockerized-DNS-Server/PowerDNS/Recursor
          file: Dockerized-DNS-Server/PowerDNS/Recursor/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}/powerdns-recursor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REPO }}/powerdns-recursor:latest
          DIGEST: ${{ steps.build-recursor.outputs.digest }}
        run: cosign sign --yes ${IMAGE}@${DIGEST}

  dnsdist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.4'


      - name: Convert repository name to lowercase
        run: echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push DNSdist
        id: build-dnsdist
        uses: docker/build-push-action@v5
        with:
          context: Dockerized-DNS-Server/PowerDNS/dnsdist
          file: Dockerized-DNS-Server/PowerDNS/dnsdist/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}/dnsdist:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REPO }}/dnsdist:latest
          DIGEST: ${{ steps.build-dnsdist.outputs.digest }}
        run: cosign sign --yes ${IMAGE}@${DIGEST}
